### ISSUE TITLE
Estimated Gas Limit when Sending Ether is inconsistent

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#294] opened 2018-12-14 03:53 UTC
When in the **Send Ether page**, and you're debugging and the senders account balance is 0.000063000000000001 ETH and a valid amount is entered that the account can afford (including the tx fee) then the Gas Limit may be shown as 21000, then as the user increases the amount to a value that the user cannot afford such that the "You don't have enough Eth balance" tooltip appears, then the Gas Limit (that is debugged with `+values.gas` in JavaScript) remains as 21000 until you increase the transaction amount from 0.000000000000000001 to a value above approx. between 0.00001-0.00009 instead, at which point the debugged Gas Limit becomes 0. I would have thought that the Gas Limit would be 0 for any amount entered above 0.000000000000000001 since above that value they cannot afford the Transaction Fee of 0.000063. 

Note: 
To debug I used the following code in TxForm.js and then opened the Developer Tools to view the values as I made changes in the UI
```
  preValidate = values => {
    const { balance, token } = this.props;
    const amount = +values.amount;
    const amountBn = new BigNumber(amount.toString());
    console.log('values: ', values);
    console.log('balance: ', balance.toString());
    console.log('balance wei: ', toWei(balance).toString());
    console.log('amount: ', amount);
    console.log('balance - amount: ', balance - amount);
    console.log('gas limit: ', +values.gas);
    console.log('gas price wei: ', toWei(values.gasPrice, 'shannon').toString());
    console.log('balance.lt(amountBn)', balance.lt(amountBn));
    console.log('balance plus gas', values.gas && values.gas.mul(toWei(values.gasPrice, 'shannon')).plus(toWei(values.amount)).toString());
    console.log('estimated tx cost (ether): ', values.gas && values.gas.mul(toWei(values.gasPrice, 'shannon')).div(1000000000000000000).toString());
    console.log('sufficient gas?', 
    values.gas && values.gas.mul(toWei(values.gasPrice, 'shannon')).plus(toWei(values.amount)).eq(toWei(balance))
    );
```

**Comment by Tbaut** [comment] 2018-12-14 09:21
I've tested it quite extensively recently, and I was able to send 1Wei by having exactly 4Gwei*21000 +1.
I don't understand what you mean with:
 >I would have thought that the Gas Limit would be 0 for any amount entered above 0.000000000000000001 since above that value they cannot afford the Transaction Fee of 0.000063.

**Comment by ltfschoen** [comment] 2018-12-14 11:02
> I've tested it quite extensively recently, and I was able to send 1Wei by having exactly 4Gwei*21000 +1.
> I don't understand what you mean with:
> 
> > I would have thought that the Gas Limit would be 0 for any amount entered above 0.000000000000000001 since above that value they cannot afford the Transaction Fee of 0.000063.

The Transaction Fee of 0.000063 corresponds to using 3 Gwei (instead of the "default" of 4 Gwei that it always switches to in the UI).
i.e. 
`3000000000 * 21000 / 10**18 = 0.000063`
where 3000000000 is 3 Gwei (Gas Price) and 21000 is the Gas Limit. We multiply them and divide by 10^18 to get the Total Transaction Fee of 0.000063 Ether (63 Mwei).

So the transaction will work if they have sufficient account balance for the tx of 0.000063000000000001, where they're trying to send a value of 1 Wei, and they've chosen 3 Gwei so the Total Tx Fee is 63 Mwei (since it uses a Gas Limit of 21000 Wei by default).
But the transaction won't work if they increase the amount they want to send to 2 Wei, and this is when the Gas Limit that's generated is 0 instead of 21000 (since it'd be an invalid tx).

If I understand you correctly, you're saying that you had an account with an account balance of 4Gwei*21000 +1 (i.e. `((4000000000 * 21000) + 1) / 10**18  = 0.000084000000000001` Ether.
If you tried to send a tx amount of 1 Wei and you changed from the "default" Gas Price of 4 Gwei down to 3 Gwei then the Total Tx Fee would be 63 Mwei, which is less than 0.000084000000000001 Ether (tx amount + total tx fee) so you would be allowed to send the transaction. And the tx would work even if you increased it up to 0.000020999999999999995 Ether (i.e. 0.000084000000000001 - 0.000063000000000001, which is your available account balance minus the total tx fee minus the tx amount). But the tx wouldn't work if you tried to send a higher amount (i.e. > 0.000020999999999999995) and the Gas Limit generated would be 0 instead of 21000 (since it'd be an invalild tx)

**Comment by Tbaut** [comment] 2018-12-17 12:33
I'm sorry but I still don't understand what the problem is for the user. It might also be that the changes that were made recently merged into master solved the problem.

I've tried to reproduce the exact scenario you mention, with 63 000 Gwei, sending 1 Wei, the estimate gas always answers 21000. I *can* send the Tx with 3 Gwei gasprice, I *can not* with more or if I send an amount > 1Wei.

The `estimateGas` is asking the node how much this type of transfer would cost, and it will not answer whether or not you have enough balance.

**Comment by Tbaut** [comment] 2019-01-23 14:55
Closing as stale. We can reopen if it happens again.

**Closed by Tbaut** 2019-01-23 14:55 UTC
Labels: M7-ui, Z1-question
